apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-minikube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikubeapp
  
  template:
    metadata:
      labels:
        app: minikubeapp
    spec:
      containers:
      - image: kishorsg/my-app:1.0.0
        name: my-app
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: minikubeapp-svc
  labels:
    app: minikubeapp
spec:
  type: NodePort
  ports:
    - port: 8075
      targetPort: 80
  selector:
    app: minikubeapp
