apiVersion: apps/v1 
kind: Deployment
metadata:
  name: deployment-minikube
spec:
  selector:
    matchLabels:
      app: minikubeapp
  
  template:
    metadata:
      labels:
        app: minikubeapp
    spec:
      containers:
      - name: minikubeapp-ctr
        image: kishorsg/my-app:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: minikubeapp-svc
  labels:
    app: minikubeapp
spec:
  type: NodePort
  ports:
    - port: 8075
      targetPort: 80
  selector:
    app: minikubeapp
